### ISSUE TITLE
Redesign home page

### ISSUE THREAD

**Issue by TheCom3di4n** [lirios/lirios.github.io#12]
## Ideas
- [x] Replace the first parallax with a screenshot of the desktop like [papyros.io](www.papyros.io) or [elementary.io](https://elementary.io/) to give visitors directly a little overview about what they can get there.
- [x] information near download button
- [ ] a grid with the official apps of Liri
- [ ] replace `<h1>` with a lettering logo (see lirios/lirios#25)

**Comment by TheCom3di4n** [comment]
I guess the whole home page needs a new look, so I renamed this issue and added a ToDo with the current ideas. I also created a screenshot with laptop frame, which would replace the first parallax. _(If you like it, I'll create a pull request.)_

Futhermore there should be some information like version and size near the download button, maybe as a little grey text below it.

![indexscreenshotdemo](https://cloud.githubusercontent.com/assets/22567618/21958363/04ca4d78-daad-11e6-863d-fd80cd53a528.png)

IMHO another good thing would it be to create/have a Material Design lettering logo ([Materialize.css logo](https://camo.githubusercontent.com/4649c8978620e21388d1170b30a9f355d80ae713/68747470733a2f2f7261772e6769746875622e636f6d2f646f6766616c6f2f6d6174657269616c697a652f6d61737465722f696d616765732f6d6174657269616c697a652e676966)), to replace the `<h1>` ("Liri"), because it looks a little bit boring at the moment.

I agree with @plfiorini, as he mentioned in #2, a grid with the official apps would look very cool, and I think I have some nice ideas for the grid but I haven't implemented it yet, so unfortunately I can't showcase you something.

_( Sorry for the bad English, I'm very tired. :sleepy: )_

**Comment by TheCom3di4n** [comment]
Which apps should be in the grid?

**Comment by TheCom3di4n** [comment]
Very basic grid

![app-grid](https://cloud.githubusercontent.com/assets/22567618/22175678/2c33fe70-dffa-11e6-878e-b84ee1e5f9e5.png)

-> Icons needed.

**Comment by plfiorini** [comment]
@TheCom3di4n Sorry for the delay. I like the grid, the apps we currently have although not all are 100% ready are (core apps and cross platform apps included):

* Files
* App Center
* Terminal
* Settings
* Browser
* Text
* Player
* Music

@TheCom3di4n BTW did you send me an email? I have seen a mail in the spam folder but I accidentally cleared the folder before reading it entirely.

**Comment by plfiorini** [comment]
And +1 for the lettering logo

**Comment by TheCom3di4n** [comment]
@plfiorini Yes, i resent the email.

I also created a new issue for the logotype in the lirios repository.

**Comment by crutchcorn** [comment]
So we're just copying Elementary's site without consideration for how their design language is different from ours?

**Comment by crutchcorn** [comment]
Updated comment to be more helpful and relevant

**Comment by TheCom3di4n** [comment]
@crutchcorn I agree with you, to copy a side wouldn't be a right step, but I don't see where we "copy" their site? I've seen things like the apps grid and the "screenshot-in-laptop-frame" on many sites and also before elementaryOS used it, furthermore they have nothing to do with the design language of elementaryOS and I think they don't harm ours (Material Design). I'm not saying that I haven't took some inspiration from their site(_...I hope they don't take it mad..._), but everyone and everything has to start anywhere and the website of Liri is more under cunstruction than finished and at a point where it's (IMHO) not bad at all to look around and get some ideas and inspirations from others and then start to combine these with our "philosophy", as you have formulated it beautifully. And I'm sure the site will meet our design goals more and more as the project progresses.

I've collected a lot of ideas and inspirations and already combined them with the MD concept - at least in my head because unfortunately I'm more the guy who can implement things than design them, so I hope that soon a few designers will spot this project and create a few concepts for the website.

**Comment by crutchcorn** [comment]
Mate, I wasn't trying to say that you're copying their site or anything. I'm playing devil's advocate (and I guess the devil too, but we all knew I was satan anyway :P) and thinking things through. I know that others have done the same and it doesn't make it the same (elementary would likely agree. I've heard the same about the dock and such from their OS). However, there has to be a point of looking at what makes our design language our design language. Inspiration is good, but can easily mislead. Their design and our design are VERY different. Even down to the underlying layout system that both languages use differ in many ways.

Instead of focusing on a grid, why not use a card based system, or [something from spec](https://material.io/guidelines/components/grid-lists.html#grid-lists-content)?
![components_grids_behavior1 1](https://cloud.githubusercontent.com/assets/9100169/22354106/b918d36a-e3d8-11e6-9e66-d38d452eb159.png)
Why not follow the [layout styling](https://material.io/guidelines/layout/principles.html) as a guideline to start with?

This way, not only will it be more similar is basic aspects, but you can [use code written by Google themselves](https://material.io/components/) in order to achieve proper visual response. 

I'm able to help with design and with implementation if needed (Full Stack Developer is my job title). Let me try to see if I can grab a minute to do some redesigns this weekend (or as soon as I can, I'll still stay for conversation any time, as that's much quicker to do)

**Comment by TheCom3di4n** [comment]
Thank you for the links!

Although I'm not very good at designing stuff as i mentioned before, I'll try to bring my ideas on paper, too, and I'm looking forward to see your concepts!

@plfiorini Does the Liri logo exist in the svg. format?

**Comment by plfiorini** [comment]
@TheCom3di4n there's one in Illustrator format here: https://github.com/lirios/artwork

This is one cancept that me and @pierremtb worked on:

![screen_shot_2017-02-14_at_14 52 15](https://cloud.githubusercontent.com/assets/843710/22966716/c00f10b8-f363-11e6-9654-4a2b6e70f084.png)

The background is going to be changed because it's too busy with the mountains and red feels weird to me

**Comment by TheCom3di4n** [comment]
The yellow/red combo looks good, but we should be careful with new colors, because I guess there's a point where we need to define a final color palette.
