### ISSUE TITLE
Some tab titles are not properly centered 

### ISSUE THREAD

**Issue by Piruzzolo** [lirios/lirios.github.io#41]
From a Huawei P9 Lite

![screenshot_2017-03-18-10-04-20](https://cloud.githubusercontent.com/assets/11365978/24070684/771ae216-0bc2-11e7-9c48-b26de9eecb6e.png)

**Comment by ajkendal** [comment]
@plfiorini 

May i work on this one as well?

I cloned the Repo. Should I fork instead, or create a branch?

**Comment by plfiorini** [comment]
@ajkendal Yes you can take this one. Fork is fine. After you have done your work you should submit a pull request.

**Comment by ajkendal** [comment]
@Piruzzolo @plfiorini 

I am trying to commit tp my branch before opening a pull request, but i am getting an error. Would you be able to help me with it?

`! [remote rejected] issue_41 -> issue_41 (push declined due to email privacy restrictions)
error: failed to push some refs to 'https://github.com/ajkendal/lirios.github.io.git'`

**Comment by ajkendal** [comment]
Nevermind I figured it out! :)

**Comment by plfiorini** [comment]
Fixed with PR #52
